# Generated by Django 3.1.6 on 2021-02-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('img_links', models.ManyToManyField(to='aparser.Image', verbose_name='Ссылки на изображения')),
            ],
        ),
    ]
