# Generated by Django 3.1.6 on 2021-02-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_links',
        ),
        migrations.AddField(
            model_name='product',
            name='img_links',
            field=models.JSONField(default=0, verbose_name='Ссылки на изображения'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
