# Generated by Django 3.1.6 on 2021-02-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0002_auto_20210217_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
    ]
