# Generated by Django 3.1.6 on 2021-02-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0004_auto_20210217_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_links',
        ),
        migrations.AddField(
            model_name='product',
            name='img_links',
            field=models.ManyToManyField(to='aparser.Image', verbose_name='Ссылки на изображения'),
        ),
    ]
