# Generated by Django 3.1.6 on 2021-02-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0005_auto_20210217_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_links',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aparser.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
