# Generated by Django 3.1.6 on 2021-02-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0006_auto_20210218_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aparser.product', verbose_name='Продукт'),
        ),
    ]
