# Generated by Django 3.1.6 on 2021-02-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0007_auto_20210218_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aparser.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
    ]
