# Generated by Django 3.1.6 on 2021-02-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0008_auto_20210218_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
